package me.mat1337.easy.gui.util.action;

public enum ActionType {

    LEFT_CLICKED,
    RIGHT_CLICKED,
    MOUSE_ENTER,
    MOUSE_LEAVE,
    PROGRESS_BAR_INCREMENT,
    PROGRESS_BAR_DECREMENT,
    SLIDER_INCREMENT,
    SLIDER_DECREMENT,
    ELEMENT_DRAG,
    ELEMENT_SCROLL,
    CHECKBOX_CHECK,
    CHECKBOX_UNCHECK,
    DROPDOWN_ITEM_SELECT,
    WINDOW_MINIMIZE,
    WINDOW_UN_MINIMIZE,
    WINDOW_CLOSE;

}